export const BACKUP_FORMAT = 'daurham-health-backup'
export const BACKUP_FORMAT_VERSION = 1
export const LATEST_SCHEMA_MIGRATION = '0034_nutrition_micros_goal_archive.sql'
export const PORTABLE_EXPORT_BYTE_LIMIT = 3_500_000

export type ColumnKind = 'uuid' | 'text' | 'date' | 'timestamptz' | 'numeric' | 'int' | 'bool' | 'json' | 'bytea'

export type BackupClass = 'canonical' | 'derived' | 'operational'

export type BackupColumn = {
  name: string
  kind: ColumnKind
}

export type BackupReference = {
  column: string
  table: string
}

export type BackupTable = {
  name: string
  backupClass: BackupClass
  primaryKey: readonly string[]
  columns: readonly BackupColumn[]
  references: readonly BackupReference[]
  /** Migration seed rows. A new database already has these, with different UUIDs. */
  seeded: boolean
  /** Included in the Settings portable download. */
  portable: boolean
}

const NEVER_EXPORT_TABLES = [
  'user',
  'session',
  'account',
  'verification',
  'jwks',
  'schema_migrations',
] as const

export const AUTH_TABLES_EXCLUDED: readonly string[] = NEVER_EXPORT_TABLES

function col(name: string, kind: ColumnKind): BackupColumn {
  return { name, kind }
}

function table(definition: BackupTable): BackupTable {
  if ((NEVER_EXPORT_TABLES as readonly string[]).includes(definition.name)) {
    throw new Error(`Refusing to export ${definition.name}`)
  }
  return definition
}

/** Parent-before-child order. This is also the restore insert order. */
export const BACKUP_TABLES: readonly BackupTable[] = [
  table({
    name: 'data_sources',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: false,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('key', 'text'),
      col('display_name', 'text'),
      col('source_kind', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'import_jobs',
    backupClass: 'operational',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('source_id', 'uuid'),
      col('imported_at', 'timestamptz'),
      col('source_filename', 'text'),
      col('format_version', 'text'),
      col('status', 'text'),
      col('record_count', 'int'),
      col('inserted_count', 'int'),
      col('matched_count', 'int'),
      col('skipped_count', 'int'),
      col('error_count', 'int'),
      col('content_hash', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'exercise_definitions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('external_id', 'text'),
      col('name', 'text'),
      col('measurement_kind', 'text'),
      col('load_type', 'text'),
      col('unilateral', 'bool'),
      col('metadata', 'json'),
      col('is_active', 'bool'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('performance_type', 'text'),
      col('analytics_load_type', 'text'),
      col('analytics_rep_mode', 'text'),
    ],
  }),
  table({
    name: 'workout_templates',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('routine_code', 'text'),
      col('version', 'text'),
      col('name', 'text'),
      col('metadata', 'json'),
      col('is_active', 'bool'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_template_exercises',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: true,
    references: [
      { column: 'workout_template_id', table: 'workout_templates' },
      { column: 'exercise_definition_id', table: 'exercise_definitions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('workout_template_id', 'uuid'),
      col('exercise_definition_id', 'uuid'),
      col('slot_id', 'text'),
      col('position', 'int'),
      col('planned_sets', 'int'),
      col('prescription', 'json'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_foods',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('name', 'text'),
      col('brand', 'text'),
      col('barcode', 'text'),
      col('catalog_kind', 'text'),
      col('serving_quantity', 'numeric'),
      col('serving_unit', 'text'),
      col('serving_grams', 'numeric'),
      col('calories', 'numeric'),
      col('protein', 'numeric'),
      col('carbs', 'numeric'),
      col('fat', 'numeric'),
      col('fiber', 'numeric'),
      col('source_kind', 'text'),
      col('is_staple', 'bool'),
      col('archived', 'bool'),
      col('notes', 'text'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'recipes',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('is_active', 'bool'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'recipe_versions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'recipe_id', table: 'recipes' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('recipe_id', 'uuid'),
      col('version', 'int'),
      col('is_current', 'bool'),
      col('name', 'text'),
      col('notes', 'text'),
      col('yield_servings', 'numeric'),
      col('finished_weight_g', 'numeric'),
      col('calories_kcal', 'numeric'),
      col('protein_g', 'numeric'),
      col('carbs_g', 'numeric'),
      col('fat_g', 'numeric'),
      col('calculation_version', 'text'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'recipe_version_ingredients',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'recipe_version_id', table: 'recipe_versions' },
      { column: 'food_id', table: 'nutrition_foods' },
    ],
    columns: [
      col('id', 'uuid'),
      col('recipe_version_id', 'uuid'),
      col('position', 'int'),
      col('food_id', 'uuid'),
      col('amount', 'numeric'),
      col('unit', 'text'),
      col('scale_factor', 'numeric'),
      col('food_name_snapshot', 'text'),
      col('food_source_type_snapshot', 'text'),
      col('food_source_external_id_snapshot', 'text'),
      col('base_serving_amount_snapshot', 'numeric'),
      col('base_serving_unit_snapshot', 'text'),
      col('base_weight_grams_snapshot', 'numeric'),
      col('base_calories_kcal_snapshot', 'numeric'),
      col('base_protein_g_snapshot', 'numeric'),
      col('base_carbs_g_snapshot', 'numeric'),
      col('base_fat_g_snapshot', 'numeric'),
      col('line_calories_kcal', 'numeric'),
      col('line_protein_g', 'numeric'),
      col('line_carbs_g', 'numeric'),
      col('line_fat_g', 'numeric'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_targets',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('effective_from', 'date'),
      col('calories_target', 'numeric'),
      col('protein_target', 'numeric'),
      col('carbs_target', 'numeric'),
      col('fat_target', 'numeric'),
      col('fiber_target', 'numeric'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_entries',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'food_id', table: 'nutrition_foods' },
      { column: 'recipe_version_id', table: 'recipe_versions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('log_date', 'date'),
      col('consumed_at', 'timestamptz'),
      col('timezone', 'text'),
      col('meal', 'text'),
      col('food_id', 'uuid'),
      col('food_name', 'text'),
      col('brand', 'text'),
      col('serving_quantity', 'numeric'),
      col('serving_unit', 'text'),
      col('grams', 'numeric'),
      col('calories', 'numeric'),
      col('protein', 'numeric'),
      col('carbs', 'numeric'),
      col('fat', 'numeric'),
      col('fiber', 'numeric'),
      col('source_kind', 'text'),
      col('notes', 'text'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('meal_group_id', 'uuid'),
      col('recipe_version_id', 'uuid'),
      col('recipe_portion_kind', 'text'),
      col('recipe_portion_amount', 'numeric'),
      col('recipe_fraction', 'numeric'),
    ],
  }),
  table({
    name: 'body_measurement_sessions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('measured_at', 'timestamptz'),
      col('timezone', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('device_name', 'text'),
      col('notes', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'body_metrics',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'measurement_session_id', table: 'body_measurement_sessions' }],
    columns: [
      col('id', 'uuid'),
      col('measurement_session_id', 'uuid'),
      col('metric_key', 'text'),
      col('value', 'numeric'),
      col('unit', 'text'),
      col('value_kind', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'body_capture_inbox',
    backupClass: 'operational',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'canonical_session_id', table: 'body_measurement_sessions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('external_capture_id', 'text'),
      col('status', 'text'),
      col('captured_at', 'timestamptz'),
      col('timezone', 'text'),
      col('metrics', 'json'),
      col('notes', 'text'),
      col('source_id', 'uuid'),
      col('canonical_session_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('committed_at', 'timestamptz'),
      col('discarded_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'body_measurement_cadences',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('metric_key', 'text'),
      col('interval_days', 'int'),
      col('enabled_from', 'date'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'lab_protocols',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('protocol_kind', 'text'),
      col('title', 'text'),
      col('description', 'text'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'lab_protocol_versions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'protocol_id', table: 'lab_protocols' }],
    columns: [
      col('id', 'uuid'),
      col('protocol_id', 'uuid'),
      col('version', 'int'),
      col('instructions', 'text'),
      col('minimum_retest_days', 'int'),
      col('suggested_retest_days', 'int'),
      col('is_current', 'bool'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'lab_protocol_requirements',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'protocol_version_id', table: 'lab_protocol_versions' }],
    columns: [
      col('id', 'uuid'),
      col('protocol_version_id', 'uuid'),
      col('position', 'int'),
      col('role', 'text'),
      col('domain', 'text'),
      col('requirement_kind', 'text'),
      col('selector', 'json'),
      col('label', 'text'),
      col('required', 'bool'),
      col('criteria', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'lab_protocol_context_controls',
    backupClass: 'canonical',
    primaryKey: ['protocol_version_id', 'tag_key'],
    seeded: false,
    portable: true,
    references: [{ column: 'protocol_version_id', table: 'lab_protocol_versions' }],
    columns: [
      col('protocol_version_id', 'uuid'),
      col('tag_key', 'text'),
      col('control_mode', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'benchmark_definitions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'protocol_id', table: 'lab_protocols' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('protocol_id', 'uuid'),
      col('domain', 'text'),
      col('description', 'text'),
      col('is_active', 'bool'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'experiments',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'protocol_version_id', table: 'lab_protocol_versions' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('title', 'text'),
      col('question', 'text'),
      col('hypothesis', 'text'),
      col('rationale', 'text'),
      col('origin', 'text'),
      col('status', 'text'),
      col('origin_kind', 'text'),
      col('origin_trigger', 'text'),
      col('origin_fingerprint', 'text'),
      col('origin_evidence', 'json'),
      col('protocol_version_id', 'uuid'),
      col('window_start', 'date'),
      col('window_end', 'date'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'experiment_benchmarks',
    backupClass: 'canonical',
    primaryKey: ['experiment_id', 'benchmark_definition_id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'experiment_id', table: 'experiments' },
      { column: 'benchmark_definition_id', table: 'benchmark_definitions' },
    ],
    columns: [
      col('experiment_id', 'uuid'),
      col('benchmark_definition_id', 'uuid'),
      col('role', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_sessions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'workout_template_id', table: 'workout_templates' },
      { column: 'experiment_id', table: 'experiments' },
      { column: 'benchmark_protocol_version_id', table: 'lab_protocol_versions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('workout_date', 'date'),
      col('workout_template_id', 'uuid'),
      col('routine_code', 'text'),
      col('template_version', 'text'),
      col('template_name', 'text'),
      col('session_type', 'text'),
      col('session_name', 'text'),
      col('experiment_id', 'uuid'),
      col('benchmark_protocol_version_id', 'uuid'),
      col('duration_min', 'numeric'),
      col('effort', 'int'),
      col('pain_level', 'int'),
      col('bodyweight_kg', 'numeric'),
      col('notes', 'text'),
      col('source_kind', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_session_exercises',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'workout_session_id', table: 'workout_sessions' },
      { column: 'exercise_definition_id', table: 'exercise_definitions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('workout_session_id', 'uuid'),
      col('exercise_definition_id', 'uuid'),
      col('position', 'int'),
      col('slot_id', 'text'),
      col('exercise_external_id', 'text'),
      col('exercise_name', 'text'),
      col('notes', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_sets',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'workout_session_exercise_id', table: 'workout_session_exercises' }],
    columns: [
      col('id', 'uuid'),
      col('workout_session_exercise_id', 'uuid'),
      col('set_number', 'int'),
      col('set_type', 'text'),
      col('load_state', 'text'),
      col('weight_kg', 'numeric'),
      col('reps', 'int'),
      col('duration_sec', 'int'),
      col('left_reps', 'int'),
      col('right_reps', 'int'),
      col('left_duration_sec', 'int'),
      col('right_duration_sec', 'int'),
      col('notes', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_transcription_jobs',
    backupClass: 'operational',
    primaryKey: ['home_ai_job_id'],
    seeded: false,
    portable: false,
    references: [{ column: 'workout_session_id', table: 'workout_sessions' }],
    columns: [
      col('home_ai_job_id', 'text'),
      col('status', 'text'),
      col('source_filename', 'text'),
      col('failure_message', 'text'),
      col('workout_session_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_capture_jobs',
    backupClass: 'operational',
    primaryKey: ['home_ai_job_id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'food_id', table: 'nutrition_foods' },
      { column: 'entry_id', table: 'nutrition_entries' },
    ],
    columns: [
      col('home_ai_job_id', 'text'),
      col('capture_kind', 'text'),
      col('status', 'text'),
      col('source_filename', 'text'),
      col('candidate_json', 'json'),
      col('failure_message', 'text'),
      col('food_id', 'uuid'),
      col('entry_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('committed_at', 'timestamptz'),
      col('user_context', 'text'),
      col('provider', 'text'),
      col('image_bytes', 'bytea'),
      col('image_mime', 'text'),
      col('interpretation', 'json'),
    ],
  }),
  table({
    name: 'nutrition_capture_images',
    backupClass: 'operational',
    primaryKey: ['home_ai_job_id', 'position'],
    seeded: false,
    portable: false,
    references: [{ column: 'home_ai_job_id', table: 'nutrition_capture_jobs' }],
    columns: [
      col('home_ai_job_id', 'text'),
      col('position', 'int'),
      col('source_filename', 'text'),
      col('image_mime', 'text'),
      col('image_bytes', 'bytea'),
      col('content_sha256', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'progress_checkpoints',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('checkpoint_date', 'date'),
      col('label', 'text'),
      col('notes', 'text'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'source_record_links',
    backupClass: 'operational',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('external_id', 'text'),
      col('external_fingerprint', 'text'),
      col('entity_type', 'text'),
      col('entity_id', 'uuid'),
      col('source_payload', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'activity_samples',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('metric_key', 'text'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('value', 'numeric'),
      col('canonical_unit', 'text'),
      col('source_unit', 'text'),
      col('source_name', 'text'),
      col('source_version', 'text'),
      col('device_name', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'sleep_intervals',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('stage', 'text'),
      col('source_category', 'text'),
      col('source_name', 'text'),
      col('source_version', 'text'),
      col('device_name', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'sleep_vital_samples',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'transport_source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('metric_key', 'text'),
      col('value_numeric', 'numeric'),
      col('unit', 'text'),
      col('observed_at', 'timestamptz'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('source_family', 'text'),
      col('transport_source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('fingerprint', 'text'),
      col('source_metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'activity_workouts',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('activity_type', 'text'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('duration_min', 'numeric'),
      col('energy_kcal', 'numeric'),
      col('distance_m', 'numeric'),
      col('source_name', 'text'),
      col('source_version', 'text'),
      col('device_name', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'activity_daily_summaries',
    backupClass: 'derived',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('summary_date', 'date'),
      col('timezone', 'text'),
      col('steps_count', 'numeric'),
      col('active_energy_kcal', 'numeric'),
      col('exercise_minutes', 'numeric'),
      col('walking_running_distance_m', 'numeric'),
      col('resting_heart_rate_bpm', 'numeric'),
      col('calculation_version', 'text'),
      col('evidence', 'json'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'sleep_nightly_summaries',
    backupClass: 'derived',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('sleep_date', 'date'),
      col('timezone', 'text'),
      col('logical_source_key', 'text'),
      col('source_name', 'text'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('total_sleep_minutes', 'numeric'),
      col('time_in_bed_minutes', 'numeric'),
      col('awake_minutes', 'numeric'),
      col('core_minutes', 'numeric'),
      col('deep_minutes', 'numeric'),
      col('rem_minutes', 'numeric'),
      col('unspecified_sleep_minutes', 'numeric'),
      col('stage_coverage_pct', 'numeric'),
      col('stage_conflict_minutes', 'numeric'),
      col('observation_status', 'text'),
      col('analysis_eligible', 'bool'),
      col('stage_analysis_eligible', 'bool'),
      col('selection_reason', 'text'),
      col('calculation_version', 'text'),
      col('evidence', 'json'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'supplements',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('name', 'text'),
      col('form', 'text'),
      col('brand', 'text'),
      col('product_name', 'text'),
      col('notes', 'text'),
      col('sort_order', 'int'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'goals',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'exercise_definition_id', table: 'exercise_definitions' },
      { column: 'benchmark_definition_id', table: 'benchmark_definitions' },
      { column: 'benchmark_protocol_version_id', table: 'lab_protocol_versions' },
      { column: 'benchmark_requirement_id', table: 'lab_protocol_requirements' },
      { column: 'supplement_id', table: 'supplements' },
    ],
    columns: [
      col('id', 'uuid'),
      col('goal_kind', 'text'),
      col('status', 'text'),
      col('started_on', 'date'),
      col('body_metric_key', 'text'),
      col('exercise_definition_id', 'uuid'),
      col('benchmark_definition_id', 'uuid'),
      col('benchmark_protocol_version_id', 'uuid'),
      col('benchmark_requirement_id', 'uuid'),
      col('supplement_id', 'uuid'),
      col('source_id', 'uuid'),
      col('paused_at', 'timestamptz'),
      col('completed_at', 'timestamptz'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'goal_versions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'goal_id', table: 'goals' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('goal_id', 'uuid'),
      col('version', 'int'),
      col('is_current', 'bool'),
      col('target_mode', 'text'),
      col('target_min', 'numeric'),
      col('target_max', 'numeric'),
      col('target_unit', 'text'),
      col('target_date', 'date'),
      col('evaluation_window_days', 'int'),
      col('notes', 'text'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'experiment_goals',
    backupClass: 'canonical',
    primaryKey: ['experiment_id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'experiment_id', table: 'experiments' },
      { column: 'goal_id', table: 'goals' },
      { column: 'goal_version_id', table: 'goal_versions' },
    ],
    columns: [
      col('experiment_id', 'uuid'),
      col('goal_id', 'uuid'),
      col('goal_version_id', 'uuid'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'supplement_schedules',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'supplement_id', table: 'supplements' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('supplement_id', 'uuid'),
      col('slot_label', 'text'),
      col('dose_amount', 'numeric'),
      col('dose_unit', 'text'),
      col('weekday_mask', 'int'),
      col('effective_from', 'date'),
      col('effective_through', 'date'),
      col('sort_order', 'int'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'supplement_status_events',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'supplement_id', table: 'supplements' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('supplement_id', 'uuid'),
      col('effective_date', 'date'),
      col('status', 'text'),
      col('notes', 'text'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'supplement_adherence',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'schedule_id', table: 'supplement_schedules' },
      { column: 'source_id', table: 'data_sources' },
    ],
    columns: [
      col('id', 'uuid'),
      col('schedule_id', 'uuid'),
      col('scheduled_date', 'date'),
      col('status', 'text'),
      col('actual_dose_amount', 'numeric'),
      col('actual_dose_unit', 'text'),
      col('taken_at', 'timestamptz'),
      col('notes', 'text'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'experiment_supplements',
    backupClass: 'canonical',
    primaryKey: ['experiment_id', 'supplement_id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'experiment_id', table: 'experiments' },
      { column: 'supplement_id', table: 'supplements' },
    ],
    columns: [
      col('experiment_id', 'uuid'),
      col('supplement_id', 'uuid'),
      col('role', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'experiment_results',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'experiment_id', table: 'experiments' },
      { column: 'protocol_version_id', table: 'lab_protocol_versions' },
      { column: 'source_id', table: 'data_sources' },
      { column: 'supersedes_result_id', table: 'experiment_results' },
    ],
    columns: [
      col('id', 'uuid'),
      col('experiment_id', 'uuid'),
      col('protocol_version_id', 'uuid'),
      col('classification', 'text'),
      col('status', 'text'),
      col('window_start', 'date'),
      col('planned_window_end', 'date'),
      col('effective_end_date', 'date'),
      col('protocol_attestation', 'text'),
      col('stopped_for_safety', 'bool'),
      col('safety_reason', 'text'),
      col('owner_note', 'text'),
      col('evidence_fingerprint', 'text'),
      col('source_id', 'uuid'),
      col('supersedes_result_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('invalidated_at', 'timestamptz'),
      col('invalidation_reason', 'text'),
    ],
  }),
  table({
    name: 'experiment_result_requirements',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'experiment_result_id', table: 'experiment_results' },
      { column: 'requirement_id', table: 'lab_protocol_requirements' },
    ],
    columns: [
      col('id', 'uuid'),
      col('experiment_result_id', 'uuid'),
      col('requirement_id', 'uuid'),
      col('evaluation_status', 'text'),
      col('summary_kind', 'text'),
      col('summary', 'json'),
      col('criterion_status', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'experiment_result_evidence',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'experiment_result_id', table: 'experiment_results' },
      { column: 'requirement_result_id', table: 'experiment_result_requirements' },
    ],
    columns: [
      col('id', 'uuid'),
      col('experiment_result_id', 'uuid'),
      col('requirement_result_id', 'uuid'),
      col('evidence_kind', 'text'),
      col('evidence_ref', 'json'),
      col('evidence_snapshot', 'json'),
      col('observation_date', 'date'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'benchmark_results',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'benchmark_definition_id', table: 'benchmark_definitions' },
      { column: 'protocol_version_id', table: 'lab_protocol_versions' },
      { column: 'experiment_id', table: 'experiments' },
      { column: 'source_id', table: 'data_sources' },
      { column: 'supersedes_result_id', table: 'benchmark_results' },
    ],
    columns: [
      col('id', 'uuid'),
      col('benchmark_definition_id', 'uuid'),
      col('protocol_version_id', 'uuid'),
      col('result_date', 'date'),
      col('experiment_id', 'uuid'),
      col('status', 'text'),
      col('protocol_confirmation_kind', 'text'),
      col('evidence_fingerprint', 'text'),
      col('source_id', 'uuid'),
      col('supersedes_result_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('invalidated_at', 'timestamptz'),
      col('invalidation_reason', 'text'),
    ],
  }),
  table({
    name: 'benchmark_result_values',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'benchmark_result_id', table: 'benchmark_results' },
      { column: 'requirement_id', table: 'lab_protocol_requirements' },
    ],
    columns: [
      col('id', 'uuid'),
      col('benchmark_result_id', 'uuid'),
      col('requirement_id', 'uuid'),
      col('value', 'numeric'),
      col('unit', 'text'),
      col('value_kind', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'benchmark_result_evidence',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'benchmark_result_value_id', table: 'benchmark_result_values' }],
    columns: [
      col('id', 'uuid'),
      col('benchmark_result_value_id', 'uuid'),
      col('evidence_kind', 'text'),
      col('evidence_ref', 'json'),
      col('evidence_snapshot', 'json'),
      col('observation_date', 'date'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'daily_context',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('context_date', 'date'),
      col('note', 'text'),
      col('source_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'daily_context_tags',
    backupClass: 'canonical',
    primaryKey: ['context_id', 'tag_key'],
    seeded: false,
    portable: true,
    references: [{ column: 'context_id', table: 'daily_context' }],
    columns: [
      col('context_id', 'uuid'),
      col('tag_key', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'ai_usage',
    backupClass: 'operational',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('request_type', 'text'),
      col('provider', 'text'),
      col('model', 'text'),
      col('request_hash', 'text'),
      col('status', 'text'),
      col('reserved_cost_usd', 'numeric'),
      col('actual_cost_usd', 'numeric'),
      col('input_tokens', 'int'),
      col('output_tokens', 'int'),
      col('created_at', 'timestamptz'),
      col('finalized_at', 'timestamptz'),
    ],
  }),
]

export function backupTable(name: string): BackupTable | undefined {
  return BACKUP_TABLES.find((item) => item.name === name)
}

export function tablesForProfile(profile: 'full' | 'portable'): readonly BackupTable[] {
  if (profile === 'full') {
    return BACKUP_TABLES
  }
  return BACKUP_TABLES.filter((item) => item.portable)
}
