export const BACKUP_FORMAT = 'daurham-health-backup'
export const BACKUP_FORMAT_VERSION = 1
export const LATEST_SCHEMA_MIGRATION = '0016_sleep_nightly_summaries.sql'
export const PORTABLE_EXPORT_BYTE_LIMIT = 3_500_000

export type ColumnKind = 'uuid' | 'text' | 'date' | 'timestamptz' | 'numeric' | 'int' | 'bool' | 'json' | 'bytea'

export type BackupClass = 'canonical' | 'derived' | 'operational'

export type BackupColumn = {
  name: string
  kind: ColumnKind
}

export type BackupReference = {
  column: string
  table: string
}

export type BackupTable = {
  name: string
  backupClass: BackupClass
  primaryKey: readonly string[]
  columns: readonly BackupColumn[]
  references: readonly BackupReference[]
  /** Migration seed rows. A new database already has these, with different UUIDs. */
  seeded: boolean
  /** Included in the Settings portable download. */
  portable: boolean
}

const NEVER_EXPORT_TABLES = [
  'user',
  'session',
  'account',
  'verification',
  'jwks',
  'schema_migrations',
] as const

export const AUTH_TABLES_EXCLUDED: readonly string[] = NEVER_EXPORT_TABLES

function col(name: string, kind: ColumnKind): BackupColumn {
  return { name, kind }
}

function table(definition: BackupTable): BackupTable {
  if ((NEVER_EXPORT_TABLES as readonly string[]).includes(definition.name)) {
    throw new Error(`Refusing to export ${definition.name}`)
  }
  return definition
}

/** Parent-before-child order. This is also the restore insert order. */
export const BACKUP_TABLES: readonly BackupTable[] = [
  table({
    name: 'data_sources',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: false,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('key', 'text'),
      col('display_name', 'text'),
      col('source_kind', 'text'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'import_jobs',
    backupClass: 'operational',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [{ column: 'source_id', table: 'data_sources' }],
    columns: [
      col('id', 'uuid'),
      col('source_id', 'uuid'),
      col('imported_at', 'timestamptz'),
      col('source_filename', 'text'),
      col('format_version', 'text'),
      col('status', 'text'),
      col('record_count', 'int'),
      col('inserted_count', 'int'),
      col('matched_count', 'int'),
      col('skipped_count', 'int'),
      col('error_count', 'int'),
      col('content_hash', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'exercise_definitions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('external_id', 'text'),
      col('name', 'text'),
      col('measurement_kind', 'text'),
      col('load_type', 'text'),
      col('unilateral', 'bool'),
      col('metadata', 'json'),
      col('is_active', 'bool'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('performance_type', 'text'),
      col('analytics_load_type', 'text'),
      col('analytics_rep_mode', 'text'),
    ],
  }),
  table({
    name: 'workout_templates',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('routine_code', 'text'),
      col('version', 'text'),
      col('name', 'text'),
      col('metadata', 'json'),
      col('is_active', 'bool'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_template_exercises',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: true,
    portable: true,
    references: [
      { column: 'workout_template_id', table: 'workout_templates' },
      { column: 'exercise_definition_id', table: 'exercise_definitions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('workout_template_id', 'uuid'),
      col('exercise_definition_id', 'uuid'),
      col('slot_id', 'text'),
      col('position', 'int'),
      col('planned_sets', 'int'),
      col('prescription', 'json'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_foods',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('name', 'text'),
      col('brand', 'text'),
      col('barcode', 'text'),
      col('catalog_kind', 'text'),
      col('serving_quantity', 'numeric'),
      col('serving_unit', 'text'),
      col('serving_grams', 'numeric'),
      col('calories', 'numeric'),
      col('protein', 'numeric'),
      col('carbs', 'numeric'),
      col('fat', 'numeric'),
      col('fiber', 'numeric'),
      col('source_kind', 'text'),
      col('is_staple', 'bool'),
      col('archived', 'bool'),
      col('notes', 'text'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_targets',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('effective_from', 'date'),
      col('calories_target', 'numeric'),
      col('protein_target', 'numeric'),
      col('carbs_target', 'numeric'),
      col('fat_target', 'numeric'),
      col('fiber_target', 'numeric'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_entries',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'food_id', table: 'nutrition_foods' }],
    columns: [
      col('id', 'uuid'),
      col('log_date', 'date'),
      col('consumed_at', 'timestamptz'),
      col('timezone', 'text'),
      col('meal', 'text'),
      col('food_id', 'uuid'),
      col('food_name', 'text'),
      col('brand', 'text'),
      col('serving_quantity', 'numeric'),
      col('serving_unit', 'text'),
      col('grams', 'numeric'),
      col('calories', 'numeric'),
      col('protein', 'numeric'),
      col('carbs', 'numeric'),
      col('fat', 'numeric'),
      col('fiber', 'numeric'),
      col('source_kind', 'text'),
      col('notes', 'text'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('meal_group_id', 'uuid'),
    ],
  }),
  table({
    name: 'body_measurement_sessions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('measured_at', 'timestamptz'),
      col('timezone', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('device_name', 'text'),
      col('notes', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'body_metrics',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'measurement_session_id', table: 'body_measurement_sessions' }],
    columns: [
      col('id', 'uuid'),
      col('measurement_session_id', 'uuid'),
      col('metric_key', 'text'),
      col('value', 'numeric'),
      col('unit', 'text'),
      col('value_kind', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_sessions',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'workout_template_id', table: 'workout_templates' }],
    columns: [
      col('id', 'uuid'),
      col('workout_date', 'date'),
      col('workout_template_id', 'uuid'),
      col('routine_code', 'text'),
      col('template_version', 'text'),
      col('template_name', 'text'),
      col('duration_min', 'numeric'),
      col('effort', 'int'),
      col('pain_level', 'int'),
      col('bodyweight_kg', 'numeric'),
      col('notes', 'text'),
      col('source_kind', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_session_exercises',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'workout_session_id', table: 'workout_sessions' },
      { column: 'exercise_definition_id', table: 'exercise_definitions' },
    ],
    columns: [
      col('id', 'uuid'),
      col('workout_session_id', 'uuid'),
      col('exercise_definition_id', 'uuid'),
      col('position', 'int'),
      col('slot_id', 'text'),
      col('exercise_external_id', 'text'),
      col('exercise_name', 'text'),
      col('notes', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_sets',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [{ column: 'workout_session_exercise_id', table: 'workout_session_exercises' }],
    columns: [
      col('id', 'uuid'),
      col('workout_session_exercise_id', 'uuid'),
      col('set_number', 'int'),
      col('set_type', 'text'),
      col('load_state', 'text'),
      col('weight_kg', 'numeric'),
      col('reps', 'int'),
      col('duration_sec', 'int'),
      col('left_reps', 'int'),
      col('right_reps', 'int'),
      col('left_duration_sec', 'int'),
      col('right_duration_sec', 'int'),
      col('notes', 'text'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'workout_transcription_jobs',
    backupClass: 'operational',
    primaryKey: ['home_ai_job_id'],
    seeded: false,
    portable: false,
    references: [{ column: 'workout_session_id', table: 'workout_sessions' }],
    columns: [
      col('home_ai_job_id', 'text'),
      col('status', 'text'),
      col('source_filename', 'text'),
      col('failure_message', 'text'),
      col('workout_session_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'nutrition_capture_jobs',
    backupClass: 'operational',
    primaryKey: ['home_ai_job_id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'food_id', table: 'nutrition_foods' },
      { column: 'entry_id', table: 'nutrition_entries' },
    ],
    columns: [
      col('home_ai_job_id', 'text'),
      col('capture_kind', 'text'),
      col('status', 'text'),
      col('source_filename', 'text'),
      col('candidate_json', 'json'),
      col('failure_message', 'text'),
      col('food_id', 'uuid'),
      col('entry_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
      col('committed_at', 'timestamptz'),
      col('user_context', 'text'),
      col('provider', 'text'),
      col('image_bytes', 'bytea'),
      col('image_mime', 'text'),
      col('interpretation', 'json'),
    ],
  }),
  table({
    name: 'progress_checkpoints',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [],
    columns: [
      col('id', 'uuid'),
      col('checkpoint_date', 'date'),
      col('label', 'text'),
      col('notes', 'text'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'source_record_links',
    backupClass: 'operational',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('external_id', 'text'),
      col('external_fingerprint', 'text'),
      col('entity_type', 'text'),
      col('entity_id', 'uuid'),
      col('source_payload', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'activity_samples',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('metric_key', 'text'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('value', 'numeric'),
      col('canonical_unit', 'text'),
      col('source_unit', 'text'),
      col('source_name', 'text'),
      col('source_version', 'text'),
      col('device_name', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'sleep_intervals',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: false,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('stage', 'text'),
      col('source_category', 'text'),
      col('source_name', 'text'),
      col('source_version', 'text'),
      col('device_name', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'activity_workouts',
    backupClass: 'canonical',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('activity_type', 'text'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('duration_min', 'numeric'),
      col('energy_kcal', 'numeric'),
      col('distance_m', 'numeric'),
      col('source_name', 'text'),
      col('source_version', 'text'),
      col('device_name', 'text'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('metadata', 'json'),
      col('created_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'activity_daily_summaries',
    backupClass: 'derived',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('summary_date', 'date'),
      col('timezone', 'text'),
      col('steps_count', 'numeric'),
      col('active_energy_kcal', 'numeric'),
      col('exercise_minutes', 'numeric'),
      col('walking_running_distance_m', 'numeric'),
      col('resting_heart_rate_bpm', 'numeric'),
      col('calculation_version', 'text'),
      col('evidence', 'json'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
  table({
    name: 'sleep_nightly_summaries',
    backupClass: 'derived',
    primaryKey: ['id'],
    seeded: false,
    portable: true,
    references: [
      { column: 'source_id', table: 'data_sources' },
      { column: 'import_job_id', table: 'import_jobs' },
    ],
    columns: [
      col('id', 'uuid'),
      col('sleep_date', 'date'),
      col('timezone', 'text'),
      col('logical_source_key', 'text'),
      col('source_name', 'text'),
      col('start_at', 'timestamptz'),
      col('end_at', 'timestamptz'),
      col('total_sleep_minutes', 'numeric'),
      col('time_in_bed_minutes', 'numeric'),
      col('awake_minutes', 'numeric'),
      col('core_minutes', 'numeric'),
      col('deep_minutes', 'numeric'),
      col('rem_minutes', 'numeric'),
      col('unspecified_sleep_minutes', 'numeric'),
      col('stage_coverage_pct', 'numeric'),
      col('stage_conflict_minutes', 'numeric'),
      col('observation_status', 'text'),
      col('analysis_eligible', 'bool'),
      col('stage_analysis_eligible', 'bool'),
      col('selection_reason', 'text'),
      col('calculation_version', 'text'),
      col('evidence', 'json'),
      col('source_id', 'uuid'),
      col('import_job_id', 'uuid'),
      col('created_at', 'timestamptz'),
      col('updated_at', 'timestamptz'),
    ],
  }),
]

export function backupTable(name: string): BackupTable | undefined {
  return BACKUP_TABLES.find((item) => item.name === name)
}

export function tablesForProfile(profile: 'full' | 'portable'): readonly BackupTable[] {
  if (profile === 'full') {
    return BACKUP_TABLES
  }
  return BACKUP_TABLES.filter((item) => item.portable)
}
