export { LabPage } from './LabPage'
export { SuggestionReviewPage } from './SuggestionPages'
export { NewExperimentPage, ExperimentDetailPage } from './ExperimentPages'
export { ReviewExperimentResultPage, ExperimentResultDetailPage } from './ExperimentResultPages'
export { NewBenchmarkPage, BenchmarkDetailPage } from './BenchmarkPages'
export { RecordBenchmarkResultPage, ReviewBenchmarkResultPage, BenchmarkResultDetailPage } from './BenchmarkResultPages'
